### ISSUE TITLE
Unable to connect to Upstart on ubuntu 16.04

### ISSUE THREAD

**Issue by 4thAce** [paulczar/cookbook-rancher#1]
When I try to converge with kitchen-vagrant I see errors relating to docker startup. In my main recipe I had it install the docker.io package.

```
           ================================================================================
           Error executing action `start` on resource 'service[docker.io]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /sbin/start docker.io ----
           STDOUT:
           STDERR: start: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
           ---- End output of /sbin/start docker.io ----
           Ran /sbin/start docker.io returned 1

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:86:in `block in run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:84:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:84:in `run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/docker/recipes/upstart.rb

            26: service docker_service do
            27:   provider Chef::Provider::Service::Upstart
            28:   supports :status => true, :restart => true, :reload => true
            29:   action [:start]
            30: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/docker/recipes/upstart.rb:26:in `from_file'

           service("docker.io") do
             provider Chef::Provider::Service::Upstart
             action [:start]
             supports {:status=>true, :restart=>true, :reload=>true}
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             service_name "docker.io"
             enabled true
             pattern "docker.io"
             declared_type :service
             cookbook_name "docker"
             recipe_name "upstart"
           end

           Platform:
           ---------
           x86_64-linux
```

Is there a workaround to get it to invoke systemd instead?

**Comment by flaccid** [comment]
@paulczar just wanted to ping and see if you will be open for contribution on this cookbook? In my org, we will be moving our provisioning to Chef and I can help maintain and update this cookbook - wanting to avoid a fork.
